version: '3.7'

services:
  app:
    image: app_vuelos:v1
    container_name: app_vuelos
    build:
      context: .
      dockerfile: Dockerfile
    env_file: '.env.development'
    ports: 
      -80:3000
    depends_on:
      - mongodb
    restart: always
    networks:
      - api_nestjs
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    enviroment:
      - MONGO_DATA_DIR=/data/db
      - MONG_LOG_DIR=/dev/null
    volumes:
      - mongodb/data/db
    expose:
      - 27017
    networks: 
      - api_nestjs

volumes:
  mongodb:

networks:
  api_nestjs: