version: '3.8'

services:
  app_dev:
    image: app_vuelos:v1
    container_name: app_vuelos_dev
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    env_file: .env.development
    ports: 
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    restart: always
    networks:
      - api_nestjs
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONG_LOG_DIR=/dev/null
    volumes:
      - mongodb:/data/db
    networks: 
      - api_nestjs

volumes:
  mongodb:

networks:
  api_nestjs:
    driver: bridge